version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    # todo: change this to widen when Dependabot adds widen back to Pip ecosystem
    # see https://github.com/dependabot/dependabot-core/pull/10194
    versioning-strategy: auto
    ignore:
      # We only use setuptools for a couple of things in the test suite
      # There is no need to keep it bleeding-edge. There are too frequent
      # updates to setuptools, requires too much maintenance to keep it up to date.
      - dependency-name: setuptools
        versions:
          - ">=72.0"
      - dependency-name: types-setuptools
        versions:
          - ">=72.0"
      # Ignore all black updates, because we use a pinned version we don't want to change
      - dependency-name: black
      # Ignore types-setuptools patch-level updates, because they issue too many!
      - dependency-name: types-setuptools
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: docker/latest/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: docker/latest/
    schedule:
      interval: weekly
    versioning-strategy: auto
  - package-ecosystem: docker
    directory: docker/unstable/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: devtools/
    schedule:
      interval: weekly
    versioning-strategy: auto
