version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: widen
    ignore:
      - dependency-name: sphinx
        versions:
          - 3.4.3
          - 3.5.2
      # Ignore all black updates, because we use a pinned version we don't want to change
      - dependency-name: black
      # Ignore types-setuptools patch-level updates, because they issue too many!
      - dependency-name: types-setuptools
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: docker/latest/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: docker/latest/
    schedule:
      interval: weekly
    versioning-strategy: widen
  - package-ecosystem: docker
    directory: docker/unstable/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: devtools/
    schedule:
      interval: weekly
    versioning-strategy: widen
