---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
# NOTE: not builing epub because epub does not know how to handle .ico files
# which results in a warning which causes the build to fail due to
# `sphinx.fail_on_warning`
# https://github.com/sphinx-doc/sphinx/issues/10350
formats:
  - htmlzip
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  fail_on_warning: true
