---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
# NOTE: not building epub because epub does not know how to handle .ico files
# which results in a warning which causes the build to fail due to
# `sphinx.fail_on_warning`
# https://github.com/sphinx-doc/sphinx/issues/10350
formats:
  - htmlzip
  - pdf

# https://docs.readthedocs.com/platform/stable/intro/mkdocs.html
build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    post_create_environment:
    # Using requirements-poetry.in as requirements-poetry.txt has conflicts with
    # the readthedocs environment.
    - pip install -r devtools/requirements-poetry.in
    post_install:
    - poetry export --only=main --only=docs --without-hashes -o requirements.txt
    - pip install --no-cache-dir -r requirements.txt
    - pip install .

mkdocs:
  configuration: mkdocs.yml
