---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
# https://docs.readthedocs.com/platform/stable/intro/zensical.html
build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    post_create_environment:
    # Using requirements-poetry.in as requirements-poetry.txt has conflicts with
    # the readthedocs environment.
    - pip install -r devtools/requirements-poetry.in
    post_install:
    # rdf4j extra is needed to document the modules in rdflib.contrib.rdf4j
    - poetry export --only=main --only=docs --extras=rdf4j --without-hashes -o requirements.txt
    - pip install --no-cache-dir -r requirements.txt
    - pip install .
    build:
      html:
      - python docs/gen_ref_pages.py
      - zensical build
    post_build:
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
