---
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
