version: "3"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    working_dir: /srv/workspace
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=1
    volumes:
      - .:/srv/workspace:z,cached
    command:
     - /bin/sh
     - -c
     - |
       echo Waiting for shutdown... override the command if this is not what you want. 1>&2
       while sleep 1000; do :; done
