version: "3"

services:
  test-runner:
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - .:/rdflib
    working_dir: /rdflib
    command: ["pytest"]

  test-runner-coverage:
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - .:/rdflib
    working_dir: /rdflib
    command: ["pytest", "--cov"]

  check-types:
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - .:/rdflib
    working_dir: /rdflib
    command: ["python", "-m", "mypy", "--show-error-context", "--show-error-codes"]
