# https://tox.wiki/en/latest/user_guide.html
# https://tox.wiki/en/latest/config.html
[tox]
minversion = 4.0.0
envlist =
    lint,
    py3{10,11,12,13,14},
    py310-extensive,
    py310-extensive-min,
    py310-lxml,
    py311-docs,
    covreport,
    docs,
    precommit
toxworkdir={env:TOX_WORK_DIR:{tox_root}/.tox}

[testenv]
deps = setuptools>=68,<72
passenv =
    DBUS_SESSION_BUS_ADDRESS # This is needed for keyring acccess on Linux.
allowlist_externals = uv
setenv =
    extensive: BERKELEYDB_DIR = /usr
    COVERAGE_FILE = {env:COVERAGE_FILE:{toxinidir}/.coverage.{envname}}
    MYPY_CACHE_DIR = {envdir}/.mypy_cache
    docs: UV_ARGS_docs = --group=docs
    extensive: UV_ARGS_extensive = --extra=berkeleydb --extra=networkx --extra=html --extra=orjson
    lxml: UV_ARGS_lxml = --extra=lxml
    py3{10,11,12,13,14}: UV_ARGS_services = --extra=rdf4j --extra=graphdb
commands_pre =
    py3{10,11,12,13,14}: python -c 'import os; print("\n".join(f"{key}={value}" for key, value in os.environ.items()))'
    py3{10,11,12,13,14}: uv lock --check
    py3{10,11,12,13,14}: uv sync --active --frozen --no-default-groups --group=dev --group=lint --group=tests {env:UV_ARGS_docs:} {env:UV_ARGS_extensive:} {env:UV_ARGS_lxml:} {env:UV_ARGS_services:} {env:UV_ARGS:}
commands =
    min: python -c 'import sys; print("min qualifier not supported on this environment"); sys.exit(1);'
    uv --version
    python -m pip freeze
    {env:TOX_EXTRA_COMMAND:}
    {env:TOX_MYPY_COMMAND:python -m mypy --show-error-context --show-error-codes --junit-xml=test_reports/{env:TOX_JUNIT_XML_PREFIX:}mypy-junit.xml}
    {posargs:{env:TOX_TEST_HARNESS:} pytest -ra --tb=native {env:TOX_PYTEST_ARGS:--junit-xml=test_reports/{env:TOX_JUNIT_XML_PREFIX:}pytest-junit.xml --cov --cov-report=} {env:TOX_PYTEST_EXTRA_ARGS:}}
    docs: python docs/gen_ref_pages.py
    docs: zensical build

[testenv:covreport]
skip_install = true
parallel_show_output = true
depends =
    py3{10,11,12,13,14}
    py310-extensive
    py310-extensive-min
    py310-lxml
    py311-docs
setenv =
    COVERAGE_FILE=
commands_pre =
    uv sync --active --frozen --only-group=tests --no-install-project
commands =
    python -m coverage combine
    python -m coverage report

[testenv:lint]
skip_install = true
commands_pre =
    uv sync --active --frozen --only-group=lint --no-install-project
commands =
    ruff check .


[testenv:docs]
basepython = python3.11
passenv =
    TERM
    DBUS_SESSION_BUS_ADDRESS
setenv =
    PYTHONHASHSEED = 0
commands_pre =
    uv lock --check
    uv sync --active --frozen --no-default-groups --group=docs --extra=html
commands =
    python docs/gen_ref_pages.py
    zensical build

[testenv:py310-extensive-min]
base = void
deps =
    pytest==7.*
    pytest-cov==4.*
    setuptools>=68,<72
setenv =
    BERKELEYDB_DIR = /usr
    COVERAGE_FILE = {env:COVERAGE_FILE:{toxinidir}/.coverage.{envname}}
    PIP_CONSTRAINT = devtools/constraints.min
extras =
    berkeleydb
    networkx
    lxml
    html
    orjson
commands =
    {envpython} --version
    pip freeze
    {posargs:{envpython} -m pytest -ra --tb=native {env:TOX_PYTEST_ARGS:--junit-xml=test_reports/{env:TOX_JUNIT_XML_PREFIX:}pytest-junit.xml --cov --cov-report=}}

[testenv:precommit{,all}]
skip_install = true
deps = pre-commit
passenv =
    HOMEPATH  # needed on Windows
    PRE_COMMIT_HOME # so that users can configure it
    XDG_CACHE_HOME # so that pre-commit won't use the default
commands =
    precommit: pre-commit run
    precommitall: pre-commit run --all-files
