ASK WHERE {
	<http://www.example.org/#ben> <http://xmlns.com/foaf/0.1/knows> ?a .
	<http://www.example.org/#ben> <http://xmlns.com/foaf/0.1/knows> ?b .
	?a <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
	?a <http://xmlns.com/foaf/0.1/name> "Mark Birbeck" .
	?b <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://xmlns.com/foaf/0.1/Person> .
	?b <http://xmlns.com/foaf/0.1/name> "Ivan Herman" .
	FILTER ( isBlank(?a) && isBlank(?b) )
}