ASK WHERE {
 <http://www.example.org/#somebody> <http://xmlns.com/foaf/0.1/knows> ?a .
 ?a <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
 ?a <http://xmlns.com/foaf/0.1/name> "Dan Brickley" .
 FILTER isBlank(?a)
}
