ASK WHERE {
	<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0113.xhtml#a> <http://purl.org/dc/elements/1.1/title> "" .
	<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0113.xhtml#b> <http://purl.org/dc/elements/1.1/title> "" .
}