ASK WHERE {
	<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0114.xhtml> <http://www.w3.org/1999/xhtml/vocab#up> <http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/rdfa-xhtml1-test-manifest.rdf> .
	<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0114.xhtml> <http://www.w3.org/1999/xhtml/vocab#prev> <http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0113.xhtml> .
	<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0114.xhtml> <http://creativecommons.org/ns#attributionURL> <http://www.w3.org/> .
}