ASK WHERE {
<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0115.xhtml>
   <http://www.example.com/entity>
      "<string>" .
<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0115.xhtml>
   <http://www.example.com/entity>
      "Ben & Co." .
<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0115.xhtml>
   <http://www.example.com/entity>
      "@" .
<http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0115.xhtml>
   <http://www.example.com/entity>
      "@" .
}
