<?xml version='1.0'?>
<fragment>
  <token>WHITESPACE</token>
  <token>UNION</token>  
  <token>COLON</token>
  <token>Q_IRI_CONTENT</token>
  <token>PNAME_NS</token>
  <token>CONSTRUCT</token>
  <token>DESCRIBE</token>
  <token>PNAME_LN</token>
  <token>BLANK_NODE_LABEL</token>
  <token>VARNAME</token>
  <token>PREFIX</token>
  <token>ASTERISK</token>
  <token>DOT</token>
  <token>QUESTION_MARK</token>
  <token>DOLLAR</token>
  <token>BASE</token>
  <token>PREFIX</token>
  <token>SELECT</token>
  <token>DISTINCT</token>
  <token>FROM</token>
  <token>NAMED</token>
  <token>OPTIONAL</token>
  <token>FILTER</token>
  <token>GRAPH</token>
  <token>WHERE</token>
  <token>ORDER</token>
  <token>BY</token>
  <token>ASC</token>
  <token>ASK</token>
  <token>DESC</token>
  <token>LIMIT</token>
  <token>OFFSET</token>
  <token>STR</token>
  <token>LANG</token>
  <token>LANGMATCHES</token>
  <token>DATATYPE</token>
  <token>isIRI</token>
  <token>isURI</token>
  <token>isLITERAL</token>
  <token>isBLANK</token>
  <token>BOUND</token>
  <token>REGEX</token>
  <token>A</token>
  <token>TRUE</token>
  <token>FALSE</token>
  <token>DOUBLE_AMPERSAND</token>
  <token>DOUBLE_PIPE</token>
  <token>BANG</token>
  <token>DOUBLE_HAT</token>
  <token>COMMA</token>
  <token>QUESTION_MARK</token>
  <token>DOLLAR</token>
  <token>FORWARDSLASH</token>
  <token>LEFT_PAREN</token>
  <token>RIGHT_PAREN</token>
  <token>LEFT_SQUARE</token>
  <token>RIGHT_SQUARE</token>
  <token>SEMICOLON</token>
  <token>INTEGER</token>
  <token>DECIMAL</token>
  <token>DOUBLE</token>
  <token>STRING_LITERAL_DELIMETER_1</token>
  <token>STRING_LITERAL_DELIMETER_2</token>
  <token>STRING_LITERAL_DELIMETER_3</token>
  <token>STRING_LITERAL_DELIMETER_4</token>
  <token>STRING_LITERAL1</token>
  <token>STRING_LITERAL2</token>
  <token>STRING_LITERAL_LONG1</token>
  <token>STRING_LITERAL_LONG2</token>
  <token>NIL</token>
  <token>ANON</token>  
  <token>LANGTAG</token>
  
  <token>LEFT_CURLY</token>
  <token>RIGHT_CURLY</token>
  
  <token>PLUS</token>
  <token>MINUS</token>
  
  <token>EQUALITY_OP</token>
  <token>NOT_EQUAL</token>
  <token>LESS_THAN</token>
  <token>GREATER_THAN</token>
  <token>LESS_THAN_EQUAL</token>
  <token>GREATER_THAN_EQUAL</token>
  
</fragment>
