name: "Test Report"
on:
  workflow_run:
    workflows: ["Validate"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      statuses: write
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: /mypy-junit-xml-(.*)$/
          name: mypy checks
          path: "*.xml"
          reporter: java-junit
      - uses: dorny/test-reporter@v1
        with:
          artifact: /pytest-junit-xml-(.*)$/
          name: pytest tests
          path: "*.xml"
          reporter: java-junit
