PREFIX : <http://example.org/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT *
{
  ?s ?p ?o .
  ?p a owl:DatatypeProperty . 
  BIND(?o+10 AS ?z)
}
