# Query13 - sameAs test

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#> 
PREFIX : <http://example.org/test#>

SELECT ?a ?b ?x
WHERE
{
  ?a :p ?b.
  ?b owl:sameAs ?x.
  ?x :q ?x.
}
