# Query6 - cycle with undistinguished variables

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/test#>

ASK
WHERE
{
:a :p _:aa.
_:aa :r _:dd.
_:dd :t _:bb.
_:bb :s :a.
}
